/*
###############################################################
#  Generated by:      Cadence Innovus 21.15-s110_1
#  OS:                Linux x86_64(Host ID cadence)
#  Generated on:      Wed Jun 24 10:25:56 2026
#  Design:            mealy_1001_1100
#  Command:           saveNetlist mealy_1001_1100_physical_netlist.v
###############################################################
*/
module mealy_1001_1100 (
	clk, 
	rst, 
	din, 
	dout_1001, 
	dout_1100, 
	dout_1101);
   input clk;
   input rst;
   input din;
   output dout_1001;
   output dout_1100;
   output dout_1101;

   // Internal wires
   wire FE_ECON13_n_13;
   wire FE_ECON12_n_15;
   wire FE_ECON11_n_15;
   wire FE_ECON10_n_15;
   wire FE_ECON9_n_9;
   wire FE_ECON8_n_9;
   wire FE_ECON7_n_17;
   wire FE_ECON6_n_17;
   wire FE_ECON5_n_17;
   wire FE_ECON4_n_17;
   wire FE_ECON1_n_17;
   wire [2:0] state;
   wire UNCONNECTED;
   wire UNCONNECTED0;
   wire UNCONNECTED1;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_15;
   wire n_16;
   wire n_17;
   wire n_23;

   BUFX2 FE_ECOC13_n_13 (.A(n_13),
	.Y(FE_ECON13_n_13));
   BUFX2 FE_ECOC12_n_15 (.A(n_15),
	.Y(FE_ECON12_n_15));
   BUFX2 FE_ECOC11_n_15 (.A(FE_ECON12_n_15),
	.Y(FE_ECON11_n_15));
   BUFX2 FE_ECOC10_n_15 (.A(FE_ECON11_n_15),
	.Y(FE_ECON10_n_15));
   BUFX2 FE_ECOC9_n_9 (.A(n_9),
	.Y(FE_ECON9_n_9));
   BUFX2 FE_ECOC8_n_9 (.A(FE_ECON9_n_9),
	.Y(FE_ECON8_n_9));
   BUFX2 FE_ECOC7_n_17 (.A(n_17),
	.Y(FE_ECON7_n_17));
   BUFX2 FE_ECOC6_n_17 (.A(FE_ECON7_n_17),
	.Y(FE_ECON6_n_17));
   BUFX2 FE_ECOC5_n_17 (.A(FE_ECON6_n_17),
	.Y(FE_ECON5_n_17));
   BUFX2 FE_ECOC4_n_17 (.A(FE_ECON5_n_17),
	.Y(FE_ECON4_n_17));
   BUFX2 FE_ECOC1_n_17 (.A(FE_ECON4_n_17),
	.Y(FE_ECON1_n_17));
   DFFRHQX1 dout_1100_reg (.CK(clk),
	.D(FE_ECON10_n_15),
	.Q(dout_1100),
	.RN(FE_ECON1_n_17));
   DFFRHQX1 dout_1101_reg (.CK(clk),
	.D(n_14),
	.Q(dout_1101),
	.RN(FE_ECON1_n_17));
   DFFRHQX1 dout_1001_reg (.CK(clk),
	.D(FE_ECON13_n_13),
	.Q(dout_1001),
	.RN(FE_ECON1_n_17));
   AOI21X1 g707__2398 (.A0(state[2]),
	.A1(n_5),
	.B0(n_7),
	.Y(n_16));
   OAI22X1 g709__5107 (.A0(n_8),
	.A1(n_12),
	.B0(n_1),
	.B1(n_2),
	.Y(n_15));
   NOR2BX1 g708__6260 (.AN(state[2]),
	.B(FE_ECON8_n_9),
	.Y(n_14));
   NOR2XL g713__4319 (.A(n_3),
	.B(n_12),
	.Y(n_13));
   NOR3X1 g710__8428 (.A(state[2]),
	.B(din),
	.C(n_4),
	.Y(n_11));
   NOR3X1 g712__5526 (.A(state[2]),
	.B(state[1]),
	.C(n_6),
	.Y(n_10));
   NOR3X1 g711__6783 (.A(state[0]),
	.B(state[1]),
	.C(din),
	.Y(n_9));
   NAND2X2 g715__3680 (.A(n_7),
	.B(n_6),
	.Y(n_8));
   NAND2X1 g716__1617 (.A(n_6),
	.B(n_4),
	.Y(n_5));
   NAND2X1 g717__2802 (.A(n_6),
	.B(din),
	.Y(n_3));
   NAND2X1 g719__1705 (.A(state[1]),
	.B(n_23),
	.Y(n_2));
   NAND2X2 g718__5122 (.A(state[2]),
	.B(n_4),
	.Y(n_12));
   NAND2X1 g714__8246 (.A(state[0]),
	.B(din),
	.Y(n_1));
   CLKINVX3 g721 (.A(din),
	.Y(n_7));
   INVXL g723 (.A(rst),
	.Y(n_17));
   CLKINVX3 g720 (.A(state[1]),
	.Y(n_4));
   CLKINVX3 g724 (.A(state[0]),
	.Y(n_6));
   DFFRX4 \state_reg[2]  (.CK(clk),
	.D(n_11),
	.Q(state[2]),
	.QN(UNCONNECTED),
	.RN(FE_ECON1_n_17));
   DFFRX4 \state_reg[1]  (.CK(clk),
	.D(n_10),
	.Q(state[1]),
	.QN(UNCONNECTED0),
	.RN(FE_ECON1_n_17));
   DFFRX4 \state_reg[0]  (.CK(clk),
	.D(n_16),
	.Q(state[0]),
	.QN(UNCONNECTED1),
	.RN(FE_ECON1_n_17));
   CLKINVX2 fopt2 (.A(state[2]),
	.Y(n_23));
endmodule

